Jrc/changes ride driver
gatitolabs/ci0156dbtypes pull request #14
Opened 2020-10-24 00:24 UTC by jrcc28

## 💬 Descripción

Se agrega el tipo de taxi en Driver, Ride y RideRequest.
Se agrega un destinationName a RideRequest.
Se agrega un status de los documentos de registro a Driver.
Se elimina el timeStamp de RideRequest.
Se agrega un date DriverDocuments.
Se unifican los datos de paymentMethod de RideRequest, Ride y Client.
Se actualiza el package.json
Nota: Se tenía prettier activado, entonces modificó algunos documentos que no lo tenían.

## ✅ Lista de Chequeo

Seleccionar todas las opciones que apliquen

- [x] Versión en `package.json` actualizada

2020-10-29 04:25 UTC, JoseAndresMejiasRojas commented
Hola @nosarabs, @dianaarias, @amesen10, @NeoCR27. Les recuerdo que tienen este pull request pendiente. Para que lo puedan revisar, por fa.

2020-10-30 20:45 UTC, nosarabs approved these changes

2020-10-30 21:10 UTC, dianaarias requested changes
Hola! Doña Maribel había pedido que agregáramos una foto de la taxista y una foto del vehículo, podrían incluir estos atributos por favor?

2020-10-30 21:37 UTC, amesen10 commented on driver.ts
> +export enum DocStatus {
Dado que es el estado del registro, se podría cambiar el nombre de la variable a requestStatus o algo similar

2020-10-30 21:37 UTC, amesen10 commented on driver.ts
> +  date: firebase.firestore.Timestamp;
El nombre podría cambiarse a algo como requestDate para que sea más mnemónico

2020-10-31 00:25 UTC, dianaarias approved these changes
Todo correcto, disculpas por el atraso!

2020-10-31 00:32 UTC, merged