update of the client data types
gatitolabs/ci0156dbtypes pull request #5
Opened 2020-10-07 04:37 UTC by andresnboza

Update of the client minimum data types and simple update of comments to acomplish DOD for client app

2020-10-07 16:20 UTC, aariasucr requested changes

2020-10-07 16:20 UTC, aariasucr commented on client.ts
> +  favoritePlaces: [FavoritePlace];
@andresnboza en typescript `[algo]` es un index signature.  Favor confirmar si esto es correcto o si hay que cambiarlo para que sea un array.

2020-10-07 16:20 UTC, aariasucr commented on client.ts
> +  solicitationTime: Date;
@andresnboza cambiar a `firebase.firestore.Timestamp` para tener un manejo estandarizado de fechas.

2020-10-07 16:20 UTC, aariasucr commented on client.ts
> +  arrival: firebase.firestore.GeoPoint;
@andresnboza en otras partes de este mismo pull request dice `algoLocation` cuando se refiere a una coordenada.  Favor actualizar para que la nomenclatura sea consistente.

2020-10-07 16:20 UTC, aariasucr commented on client.ts
> +  solicitationTime: Date;
@andresnboza favor cambiar `solicitation` por algo como `request`.  Solicitation se aplica mas al ofrecimiento de bienes o servicios, en lugar de una solicitud

2020-10-07 16:20 UTC, aariasucr commented on client.ts
> +  code: string;
@andresnboza comentario no concuerda con el nombre

2020-10-07 16:20 UTC, aariasucr commented on client.ts
> +export interface ClientLocation {
@andresnboza inconsistencia en idioma de los comentarios

2020-10-07 16:24 UTC, aariasucr commented
@dianaarias @dianaarias puedes confirmar por favor si los comentarios para intellisense deben estar en ingles o en español?  Esto para mantener consistencia, porque en el PR https://github.com/gatitolabs/ci0156dbtypes/pull/4 los comentarios estan en español, y aqui hay varios en ingles, para no terminar con un spanglish.

2020-10-07 17:05 UTC, nosarabs commented
> @dianaarias @dianaarias puedes confirmar por favor si los comentarios para intellisense deben estar en ingles o en español? Esto para mantener consistencia, porque en el PR #4 los comentarios estan en español, y aqui hay varios en ingles, para no terminar con un spanglish.

Yo sé que no estoy como reviewer en este PR pero bueno debería, así que te dejo el mismo comentario que en el PR #4. 

Los comentarios deberían de estar en **español**, porfa intenten mantener el formato para que la documentación interna se mantenga bonita 😁. Acá te dejo un ejemplo de como se debería comentar una interfaz y un atributo de la misma.
<img width="516" alt="Screen Shot 2020-10-07 at 10 39 50" src="https://user-images.githubusercontent.com/26913909/95361835-77011200-088a-11eb-8cfc-ef3797169452.png">

También recuerden asignarnos tanto a Diana como a mí de reviewers en los PR que modifiquen archivos de backend.

2020-10-07 17:07 UTC, nosarabs commented
También me parece que está demás cambiar los comentarios en los atributos e interfaces que ya están establecidos.

2020-10-07 18:04 UTC, andresnboza commented on client.ts
> +  favoritePlaces: [FavoritePlace];
Esto seria para un arreglo de instancias de Favorite places por lo que estamos guardando objetos de tipo Favorite place en un arreglo, pensaba que esta era la manera de decir que es un arreglo de instancias de FavoritePlace

2020-10-07 18:05 UTC, andresnboza commented on client.ts
> +  solicitationTime: Date;
listo

2020-10-07 18:06 UTC, aariasucr commented on client.ts
> +  favoritePlaces: [FavoritePlace];
para definirlo como arreglo seria `favoritePlaces: FavoritePlace[];`

2020-10-07 18:06 UTC, andresnboza commented on client.ts
> +  arrival: firebase.firestore.GeoPoint;
listo

2020-10-07 18:11 UTC, andresnboza commented on client.ts
> +  solicitationTime: Date;
listo

2020-10-07 18:11 UTC, andresnboza commented on client.ts
> +  code: string;
listo

2020-10-07 18:39 UTC, andresnboza commented on client.ts
> +export interface ClientLocation {
ya cambié los comentarios a español

2020-10-07 19:56 UTC, aariasucr approved these changes
@andresnboza sin mas comentarios de mi parte.  Favor esperar a la aprobacion de @dianaarias o @nosarabs antes de hacer merge de este PR

2020-10-07 22:26 UTC, dianaarias reviewed
@andresnboza Adicionalmente a los comentarios/dudas, también queda el mínimo detalle de que hay algunos typos en las descripciones de algunos atributos. Cada vez que se utiliza clientFirebaseID en los comentarios sale "clienFirebaseID" y en algunos otros se usa la palabra "usario" en lugar de "usuario". Me parece que estos typos ya estaban ahí, pero si podés corregirlos de una sería excelente! Gracias.

2020-10-07 22:26 UTC, dianaarias commented on client.ts
>    deleted: boolean;
@andresnboza  Veo que el comentario original era "to make logic deletes". Este atributo se utiliza solo para esto, o es útil en general para determinar el estado del usuario en el sistema? En el segundo caso podría ser útil usar un enum Status de la misma manera que en driver.ts y cambiar el nombre del atributo "deleted" a "status"; para mantener la consistencia.

2020-10-07 22:26 UTC, dianaarias commented on client.ts
> +  departureLocation: firebase.firestore.GeoPoint;
@andresnboza En este caso, veo que originalmente el atributo se llamaba currentLocation, y para está interfaz quizá sea más relevante que se llame de esa manera.

2020-10-08 01:07 UTC, andresnboza commented on client.ts
>    deleted: boolean;
Ya le hice el enum y le cambié el nombre a algo mas significativo y util para la app

2020-10-08 01:09 UTC, andresnboza commented on client.ts
> +  departureLocation: firebase.firestore.GeoPoint;
listo

2020-10-08 03:28 UTC, dianaarias approved these changes
Listo, no tengo más comentarios. Nada más recordar añadirnos tanto a @nosarabs como a mi para que cualquiera de las dos pueda revisar/aprobar cambios!

2020-10-08 03:36 UTC, merged

2020-10-08 16:18 UTC, nosarabs commented
@andresnboza porfas revisa estos comentarios para que podas terminar de hacer el proceso de integracion a backend cuando este el tag listo.
https://github.com/gatitolabs/ci0156dbtypes/pull/4#issuecomment-705636194
https://github.com/gatitolabs/ci0156dbtypes/pull/4#issuecomment-705650589